fix: volume map to default Docker Deskotp file sharing (/Users)
blinklabs-io/cardano-up pull request #211
Opened 2024-05-01 17:43 UTC by verbotenj

fixes #188

2024-05-01 20:07 UTC, agaffney requested changes
This is going to break on Linux. You need to do some OS detection in the script to change the handling for the host paths a bit.

2024-05-01 20:07 UTC, agaffney commented on packages/cardano-cli/files/cardano-cli.sh.gotmpl
> +	-w $(pwd) \
We want to keep the `/host` prefix for consistency

2024-05-01 20:07 UTC, agaffney commented on packages/mithril-client/files/mithril-client.sh.gotmpl
> +		k="${k}"
Keep the `/host` prefix

2024-05-01 20:07 UTC, agaffney commented on packages/mithril-client/files/mithril-client.sh.gotmpl
> +	-w $(pwd) \
Keep the `/host` prefix

2024-05-07 14:04 UTC, wolf31o2 approved these changes

2024-05-07 16:15 UTC, merged